### ISSUE TITLE
Instance name defined in a text macro doesn't work

### ISSUE THREAD

**Issue by sgherbst** [sgherbst/pysvinst#10]
Example:
```verilog
`define MOD_INST u_mysubmod
module mymod;
mysubmod `MOD_INST (); 
endmodule
```
Output:
```yaml
files:
  - file_name: "some_file.sv"
    defs:
      - mod_name: "mymod"
        insts:
```
Expected:
```yaml
files:
  - file_name: "some_file.sv"
    defs:
      - mod_name: "mymod"
        insts:
          - mod_name: "mysubmod"
            inst_name: "u_mysubmod"
```
